name: graco
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - cudatoolkit=11.3
  - dask
  - jupyter
  - networkx
  - matplotlib
  - pandas
  - pip
  - pyyaml
  - wheel
  - zarr
  - pip:
    - epynet
    - optuna
    - pyDOE2
    - ray
    - torchinfo
